services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: svelte-app-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      # - /app/.svelte-kit
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
